spring:
  datasource:
    url: jdbc:h2:mem:lab02s02;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create   
    show-sql: true
    defer-datasource-initialization: true  

  sql:
    init:
      mode: always
      encoding: UTF-8     

  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /swagger-ui.html
